export const MoviedbActionTypes = {
  REQUEST_TOP_MOVIES_START: "REQUEST_TOP_MOVIES_START",
  REQUEST_TOP_MOVIES_SUCCESS: "REQUEST_TOP_MOVIES_SUCCESS",
  REQUEST_TOP_MOVIES_FAILED: "REQUEST_TOP_MOVIES_FAILED",
};
