export const MoviedbActionTypes = {
  REQUEST_MOVIEDB_START: 'REQUEST_MOVIEDB_START',
  REQUEST_TOP_MOVIES_SUCCESS: 'REQUEST_TOP_MOVIES_SUCCESS',
  REQUEST_MOVIEDB_FAILED: 'REQUEST_MOVIEDB_FAILED',
  REQUEST_POPULAR_MOVIES_SUCCESS:'REQUEST_POPULAR_MOVIES_SUCCESS',
  REQUEST_UPCOMING_MOVIES_SUCCESS:'REQUEST_UPCOMING_MOVIES_SUCCESS',
  REQUEST_NOWPLAYING_MOVIES_SUCCESS:'REQUEST_NOWPLAYING_MOVIES_SUCCESS',
  REQUEST_POPULAR_TV_SUCCESS:'REQUEST_POPULAR_TV_SUCCESS',
  REQUEST_TOP_RATED_TV_SUCCESS:'REQUEST_TOP_RATED_TV_SUCCESS'
};
